### ISSUE TITLE
cambio de verso

### ISSUE THREAD

**Issue by NildaBernal** [NildaBernal/Sensores-N4-Equipo5#1]
Quisiera cambiar la estrofa No.3:
"Actuando como un robot 
Es cerebro de metal corroido 
**Tratas de tomarle el pulso
Antes de que la cabeza explote**"

que me recomiendan poner en su lugar?

**Comment by NildaBernal** [comment]
"Actuando como un robot 
Es cerebro de metal corroido 
**Intentas cambiar su opinión
Antes de que haga su destrucción**"
 
podría ser una opción

**Comment by nashuk** [comment]
Cuando caes en rutina 
Tu mente empieza a fallecer 
Tratas de girar tu rumbo
Sin otra opcion tener
